### PR TITLE
GNOME 48 Support

### LINKED ISSUE #112: not working in gnome 48
today i got gnome48 beta on my debian sid but search light extensions is not working although in metadata file i added "48"

### PR DESCRIPTION
**Pull request by cryptbrn**
Implement port guide for GNOME48 (https://gjs.guide/extensions/upgrading/gnome-shell-48.html#gjs)

closes #112

### CODE REVIEW

**Comment by Belsedar** [comment]
This Pr fixes the extension for me on Gnome 1:48.0-1 on Arch. Thanks a lot!

**Comment by geekosaurusR3x** [comment]
Fix for me too

**Comment by eboye** [comment]
Works for some time, but then it throws:

```log
TypeError: (intermediate value).enable_unredirect_for_display is not a function
```

**Comment by andylvua** [comment]
Thank you a lot! Works for me on GNOME Shell `48.0`, `6.12.20-2-MANJARO`.

**Comment by faketi101** [comment]
> Thank you so much, it works perfectly!

can you share?

**Comment by faketi101** [comment]
> Works on `GNOME 48.0`, `6.1.132-1-MANJARO`

can you share the file please?

**Comment by faketi101** [comment]
man its worked 
thanks a lot

**Comment by thethomasboyer** [comment]
works for me too, thanks a lot!

**Comment by tulilirockz** [comment]
Seems to break GNOME 47 - `Error: No property orientation on StBoxLayout`. Dunno if this is my local thing or the PR's fault

**Comment by anuragtyagi-dev** [comment]
> man its worked thanks a lot

Can you share the file or the method how to make it work , sorry I'm not getting the steps.

**Comment by lubdhak7414** [comment]
Working perfectly for gnome-shell-48.1-1 in Fedora 42 Workstation.

**Comment by pierrebrd** [comment]
Works well on Ubuntu 25.04 with Gnome 48. @icedman , do you think this could be merged soon? Thanks in advance :)

**Review by semuaakunada — APPROVED** [review]

**Comment by brunos3d** [comment]
For those early adopters who wants to try the PR changes proposed by @cryptbrn, just run

```sh
cd /tmp && git clone git@github.com:cryptbrn/search-light.git && cd search-light && make
```

@cryptbrn thank you for the solution! :rocket:

**Review by brunos3d — APPROVED** [review]
Not 100% sure but for retrocompatibility we should make sure the old functions are available before calling or using the new ones.

Anyway, if it works for previous Gnome Shell versions LGTM :rocket:

**Comment by b2nzy** [comment]
Works on `GNOME 48` `6.14.3-1-cachyos-bore`

**Comment by goodpeople34** [comment]
work perfectly in gnome 48 ubuntu 25.04. thanks!

**Comment by robinhickmann** [comment]
@icedman, is there a reason you haven't merged this, would be nice to put out a new version on the gnome extensions store that has support for gnome 48.

**Review by DylanBrass — APPROVED** [review]

**Comment by robinhickmann** [comment]
We don't need more people saying this looks good and approving the changes, unless it's someone with access to merge the pr. I think if you scroll up, it's pretty clear that this fix looks good.

**Comment by xoity** [comment]
why hasnt this been merged yet?
